const types = {
  SETTINGS_DARKMODE: "SETTINGS_DARKMODE",
  SETTINGS_LANGUAGE: "SETTINGS_LANGUAGE",
  MENU_OPEN: "MENU_OPEN",
  MENU_PAGE: "MENU_PAGE",
  RCCC_UPDATE: "RCCC_UPDATE",
  SW_INIT: "SW_INIT",
  SW_UPDATE: "SW_UPDATE",
};

export default types;
